### ISSUE TITLE
Upgrade to new one-true-path-experiment major version

### ISSUE THREAD

**Issue by etaque** [gampleman/elm-visualization#110]
Hello Jakub,
@folkertdev just released a [new version](https://github.com/folkertdev/one-true-path-experiment/compare/5.0.2...6.0.0) of one-true-path-experiment, with fixes for path and floating number coordinates parsing. Unfortunately the path parser fix imply a major version bump for it, so elm-visualization can't match it. Would you mind bumping this version dep? (I can make a PR to prepare this).
Have a nice day,
Emilien

**Comment by gampleman** [comment]
Yea if you have a chance to make a PR, that would be much appreciated! Also do you need this released anytime soon?

**Comment by etaque** [comment]
Yes, that would be great! But if you don't have time for that, I'll find a workaround.

**Comment by etaque** [comment]
> Also do you need this released anytime soon?

I don't need it soon anymore, found a workaround. Anyway, still available to move this forward if you wish!

**Comment by gampleman** [comment]
OK, let me know if that changes (or anyone else). Otherwise we'll ship this as part of 2.2.
