### ISSUE TITLE
Renamed dependency breaks builds

### ISSUE THREAD

**Issue by mingan** [gampleman/elm-visualization#159]
`ryannhg/date-format` 2.3.0` was renamed to `ryan-haskell/date-format` 1.0.0. Due to how the rename was done by the author fresh builds (e.g. on CI) now fail. If it was a direct dependency, we'd just rename it but we depend on it through elm-visualization. It needs to rename the dependency.

Upstream issue: https://github.com/ryan-haskell/date-format/issues/39, Discourse thread: https://discourse.elm-lang.org/t/username-changed/9705.

**Comment by gampleman** [comment]
Closed by #159.
