### ISSUE TITLE
Um, it's awesome!!!!

### ISSUE THREAD

**Issue by madasebrof** [gampleman/elm-visualization#16]
No issue, just wanted to say thank you for bringing D3 to Elm!

Amazing, super, wow.

Better than D3. (For what I'm doing!)

This + TypedSVG is super powerful.

Rock on,

Adam

**Comment by gampleman** [comment]
Thank you 😊 

(Yeah I think TypedSVG makes a really good combo. In fact I'm thinking of porting the examples to use just to encourage people to try both of the libraries together).

**Comment by madasebrof** [comment]
Sounds like a good idea. That's the first thing I did--port the examples to TypedSVG so I could better understand them. Also, makes for much cleaner looking code and fits nicely with Elm Html (obviously).
