### ISSUE TITLE
Examples website is unavailable

### ISSUE THREAD

**Issue by Anton-4** [gampleman/elm-visualization#166]
https://elm-visualization.netlify.com/ shows "Site not found"

**Comment by gampleman** [comment]
Sigh. Netlify nixed that and only serves it now under https://elm-visualization.netlify.app. See https://answers.netlify.com/t/deprecating-automatic-com-redirects/115442/7.

I'll try to get a new patch version out with the links updated out early next week, but PRs definitely welcome until then if anyone is interested.

**Comment by Anton-4** [comment]
PR is ready :)
