### ISSUE TITLE
tickCount not working for ContinuousTimeScale?

### ISSUE THREAD

**Issue by SimonPersson** [gampleman/elm-visualization#18]
I hope I have not simply misunderstood the docs :) From my understanding though, the `Options` passed to `Axis.axis` has a `tickCount` that determines roughly how many ticks to generate. This does not seem to work for me. I created a gist based on the line chart example, where I set `tickCount = 5` on both axis, yet the x-axis has way too many ticks:

https://gist.github.com/SimonPersson/85e571756b20d94b6d8f9eca8a37fa1e

**Comment by gampleman** [comment]
The `tickCount` is merely a hint - generally the provided tick functions still try to find "nice" points where to make ticks. In the case of time, the maximum resolution at which nice time points are found is at the level of years. In the gist above time range is so large that you would probably want centuries.

Doing something smarter for decades or centuries could be an option, but at some point you need to provide your own custom ticks - which is what the `ticks` option in Axis is for:

```
import Date exposing (Month(..))
import Date.Extra exposing (fromParts)

xAxis : List ( Date, Float ) -> Svg msg
xAxis model =
    Axis.axis
        { defaultOptions
            | orientation = Axis.Bottom
            , ticks =
                Just
                    [ fromParts 2000 Jan 1 0 0 0 0
                    , fromParts 2050 Jan 1 0 0 0 0
                    , fromParts 2100 Jan 1 0 0 0 0
                    , fromParts 2150 Jan 1 0 0 0 0
                    , fromParts 2200 Jan 1 0 0 0 0
                    ]
        }
        xScale
```

**Comment by SimonPersson** [comment]
Yeah, I see how generating ticks for a time scale with any resolution can be a hard problem. Thanks, I'll add the ticks myself using the `ticks` option.
