### ISSUE TITLE
Examples url not reachable 

### ISSUE THREAD

**Issue by alltonp** [gampleman/elm-visualization#20]
Hi,

This looks nice, is this project still alive? 

The link to the examples (http://code.gampleman.eu/elm-visualization/) seems to be broken, DNS unreachable.

Paulos

**Comment by gampleman** [comment]
Yes, sorry DNS trouble while on holiday away from laptop. I've just merged a PR that changes the link to a [mirror](http://paws.kettering.edu/%7Esturgmancohen/elm-visualization/), so you can continue to view the docs from there.

**Comment by alltonp** [comment]
Great, thank you.

**Comment by gampleman** [comment]
OK, this looks like it now works.

**Comment by Razzeee** [comment]
Did this happen again?

**Comment by gampleman** [comment]
Yes. 😊 

I've prepaid the domain for the next five years now...
