### ISSUE TITLE
Upgrade elm-community/list-extra

### ISSUE THREAD

**Issue by sporto** [gampleman/elm-visualization#25]
This package uses elm-community/list-extra v6.Meaning that it cannot be used with project using elm-community/list-extra v7 (our case). Please upgrade.

**Comment by gampleman** [comment]
Hi, I'd love to upgrade, but unfortunately I'm blocked by downstream packages, so until https://github.com/folkertdev/one-true-path-experiment/issues/3 is resolved and released, I'm afraid this won't happen.
