### ISSUE TITLE
Potential issue with Scale.nice and logarithmic scale around 0 

### ISSUE THREAD

**Issue by hamidzr** [gampleman/elm-visualization#64]
When the logarithmic `Scale.nice` is applied to `Scale.log` with a positive domain close to 0 it causes the final resulting domain to be reversed eg, (9, 4)
The resulting plot axis ends up being reversed.

I'll provide more details with examples

**Comment by gampleman** [comment]
@hamidzr If you could kindly produce an example that reproduces this, it would be great. I will close this otherwise. Thanks.
