### ISSUE TITLE
ForceDirectedGraph example: node does not follow mouse on drag.

### ISSUE THREAD

**Issue by Anton-4** [gampleman/elm-visualization#89]
Clicking on a circle results the circle to be displaced with some offset from the mouse.
This offset gets larger as the drag coordinates get larger.
So at (x:0, y:0) the circle is located at the position of the mouse, for larger coordinates this is no longer the case. This offset getting larger implies the drag coordinates are erroneously multiplied by some factor.

I looked around somewhat but could not find the cause of this bug.

![image](https://user-images.githubusercontent.com/17049058/84065345-877cab00-a9c4-11ea-99f6-1ec90d78c376.png)
![image](https://user-images.githubusercontent.com/17049058/84065369-8ea3b900-a9c4-11ea-8a42-c22d019ab86f.png)
![image](https://user-images.githubusercontent.com/17049058/84065376-93686d00-a9c4-11ea-8ede-fbbce1bc3c0d.png)

**Comment by gampleman** [comment]
Did you get this issue when running the example in isolation (aka outside the examples website?)

This is a problem with responsive SVG scaling. I've been working on solutions but Elm is unfortunately missing some SVG methods to make this straightforward. You can see https://github.com/gampleman/elm-visualization/pull/86 for an example that solves this problem.

**Comment by Anton-4** [comment]
Yes it did happen in isolation.

Alright, I'll see if I can transfer the solution from #86.

**Comment by gampleman** [comment]
We'll merge #86 soon-ish. I'd like to keep some of the complexity out if possible. I suspect that the simplest solution for this would be just to set the SVG width and height attributes.

**Comment by gampleman** [comment]
AFAIK this can be closed? I don' think there is a staightforward fix, apart from doing some of the stuff in the example.
